### ISSUE TITLE
compiler error on macos, ide vscode

### ISSUE THREAD

**Issue by wangdanqing** [kuaifengle/Flutter-WeChat#1]
-------------------my env as follower
Flutter 1.7.8+hotfix.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 20e59316b8 (3 weeks ago) • 2019-07-18 20:04:33 -0700
Engine • revision fee001c93f
Tools • Dart 2.4.0

-------------------error message as follower
**Compiler message:
file:///Users/xx/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_sticky_header-0.3.4/lib/src/widgets/sticky_header
_layout_builder.dart:147:16: Error: The argument type 'String' can't be assigned to the parameter type 'DiagnosticsNode'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart'
 ('file:///Users/xx/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'DiagnosticsNode'.
      context: context);**

**Comment by dulumao** [comment]
+1
