### ISSUE TITLE
运行不起来

### ISSUE THREAD

**Issue by 946572411** [kuaifengle/Flutter-WeChat#3]
![image](https://user-images.githubusercontent.com/37761691/120894880-3510b180-c64d-11eb-904b-5547715a8b75.png)
运行环境：
![image](https://user-images.githubusercontent.com/37761691/120894923-5e314200-c64d-11eb-9d4c-0b609766df54.png)

**Comment by kuaifengle** [comment]
你这个都稳定版本2.2.1了，等我有空再去修改版本引起问题把
